Repository angr/angr-management, pull requests merged in 2021-07, with the labels that each got.

#367 Do not restore zoom level when jumping to a new function. Fix #365.
  angrmanagement/ui/views/disassembly_view.py
Labels: bug

#377 fixed a bad-am_obj-use bug
  angrmanagement/plugins/trace_viewer/qtrace_viewer.py
Labels: bug

#219 Variable name prediction UI support.
  angrmanagement/config/config_manager.py
  angrmanagement/plugins/varec/__init__.py
  angrmanagement/plugins/varec/varec.py
  angrmanagement/ui/dialogs/rename_node.py
  angrmanagement/ui/menus/analyze_menu.py
  angrmanagement/ui/workspace.py
Labels: feature

#387 Serializing variable names and codegens into angr DB
  angrmanagement/data/instance.py
  angrmanagement/data/jobs/decompile_function.py
  angrmanagement/plugins/binsync/sync_ctrl.py
  angrmanagement/ui/main_window.py
  angrmanagement/ui/views/code_view.py
Labels: feature

#389 Support manually connecting to the CHECRS backend.
  angrmanagement/__main__.py
  angrmanagement/plugins/base_plugin.py
  angrmanagement/plugins/chess_manager/__init__.py
  angrmanagement/plugins/chess_manager/backend_selector_dialog.py
  angrmanagement/plugins/chess_manager/chess_connector.py
  angrmanagement/plugins/chess_manager/chess_url_handler.py
  angrmanagement/plugins/plugin_manager.py
  angrmanagement/ui/main_window.py
  angrmanagement/ui/workspace.py
Labels: feature

#391 Add a status bar button to show the status of CHECRS connection.
  angrmanagement/__main__.py
  angrmanagement/config/__init__.py
  angrmanagement/config/config_entry.py
  angrmanagement/config/config_manager.py
  angrmanagement/daemon/url_handler.py
  angrmanagement/logic/threads.py
  angrmanagement/plugins/base_plugin.py
  angrmanagement/plugins/chess_manager/backend_selector_dialog.py
  angrmanagement/plugins/chess_manager/chess_connector.py
  angrmanagement/plugins/chess_manager/connected.png
  angrmanagement/plugins/chess_manager/connecting.png
  angrmanagement/plugins/chess_manager/disconnected.png
  angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py
  angrmanagement/plugins/log_reverse_engineering/log_reverse_engineering_plugin.py
  angrmanagement/plugins/plugin_manager.py
  angrmanagement/plugins/trace_viewer/multi_trace.py
  angrmanagement/ui/main_window.py
Labels: feature

#394 QCCodeEdit: Do not raise exception when empty.
  angrmanagement/ui/widgets/qccode_edit.py
Labels: bug

#396 GraphLayouter: Fix a crash with graphs involving a single node with self-loops.
  angrmanagement/utils/graph_layouter.py
Labels: bug

#395 Refactor BinSync
  angrmanagement/plugins/binsync/binsync_plugin.py
  angrmanagement/plugins/binsync/controller.py
  angrmanagement/plugins/binsync/ui/__init__.py
  angrmanagement/plugins/binsync/ui/config_dialog.py
  angrmanagement/plugins/binsync/ui/info_panel.py
  angrmanagement/plugins/binsync/ui/info_tables/__init__.py
  angrmanagement/plugins/binsync/ui/info_tables/func_info_table.py
  angrmanagement/plugins/binsync/ui/info_tables/struct_info_table.py
  angrmanagement/plugins/binsync/ui/sync_menu.py
Labels: refactor

#393 Add two plugins: `ExecutionStatisticsViewer` and `SourceViewerPlugin`
  angrmanagement/plugins/execution_statistics_viewer/__init__.py
  angrmanagement/plugins/execution_statistics_viewer/execution_statistics_viewer.py
  angrmanagement/plugins/source_viewer/__init__.py
  angrmanagement/plugins/source_viewer/source_viewer_plugin.py
Labels: feature

#403 ChessConnector: Implements a CHESS target selector.
  angrmanagement/plugins/base_plugin.py
  angrmanagement/plugins/chess_manager/chess_connector.py
  angrmanagement/plugins/chess_manager/target_selector.py
  angrmanagement/plugins/plugin_manager.py
  angrmanagement/ui/main_window.py
  angrmanagement/ui/widgets/qstring_table.py
Labels: feature

#410 Speed up RDA during dependency analysis.
  angrmanagement/data/jobs/dependency_analysis.py
  angrmanagement/ui/views/dep_view.py
  angrmanagement/utils/tree_graph_layouter.py
Labels: feature

#412 Only prompt registering angr:// URL scheme in CHECRS mode.
  angrmanagement/__main__.py
  angrmanagement/ui/main_window.py
Labels: refactor
