Repository angr/angr-management, pull requests merged in 2021-09, with the labels that each got.

#430 Variable retyping in pseudocode view
  angrmanagement/data/jobs/decompile_function.py
  angrmanagement/plugins/binsync/controller.py
  angrmanagement/ui/dialogs/retype_node.py
  angrmanagement/ui/dialogs/type_editor.py
  angrmanagement/ui/view_manager.py
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/views/disassembly_view.py
  angrmanagement/ui/views/types_view.py
  angrmanagement/ui/views/view.py
  angrmanagement/ui/widgets/qccode_edit.py
  angrmanagement/ui/widgets/qtypedef.py
  angrmanagement/ui/workspace.py
Labels: feature

#470 Remove cached decompilation result when decompilation options are dirty.
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/widgets/qdecomp_options.py
Labels: bug

#471 QLinearViewer: Fix issues with displaying AIL blocks.
  angrmanagement/ui/widgets/qlinear_viewer.py
Labels: bug

#472 Fix the text on the save patched binary button. Close #469.
  angrmanagement/ui/views/patches_view.py
Labels: bug

#473 Log view
  angrmanagement/__main__.py
  angrmanagement/data/instance.py
  angrmanagement/data/log.py
  angrmanagement/resources/images/benchmark-icon.png
  angrmanagement/resources/images/error-icon.png
  angrmanagement/resources/images/warning-icon.png
  angrmanagement/ui/dialogs/preferences.py
  angrmanagement/ui/menus/log_menu.py
  angrmanagement/ui/views/__init__.py
  angrmanagement/ui/views/log_view.py
  angrmanagement/ui/widgets/qlog_widget.py
  angrmanagement/ui/workspace.py
Labels: feature

#474 CodeView: Show text cursor when tabbed from disassembly view.
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/workspace.py
Labels: bug

#475 QDecompilationOptions: Implement search feature. Close #448.
  angrmanagement/ui/widgets/qdecomp_options.py
Labels: feature

#476 Changing color scheme without decompilation result should not crash. Closes #449.
  angrmanagement/ui/views/code_view.py
Labels: bug

#477 QLogWidget: Speed up log displaying.
  angrmanagement/ui/widgets/qlog_widget.py
Labels: enhancement

#491 Allow removing patches and editing comments in Patches view
  angrmanagement/ui/widgets/qpatch_table.py
Labels: feature

#493 QLogIcons: Delay QIcon creation until first use to make QGuiApplication-less tests pass.
  angrmanagement/ui/widgets/qlog_widget.py
Labels: bug

#500 Display splash screen sooner.
  angrmanagement/__main__.py
  angrmanagement/ui/views/console_view.py
Labels: enhancement
