Repository angr/angr-management, pull requests merged in 2021-06, with the labels that each got.

#271 CHESS manager plugin
  angrmanagement/daemon/server.py
  angrmanagement/daemon/url_handler.py
  angrmanagement/plugins/chess_manager/__init__.py
  angrmanagement/plugins/chess_manager/chess_url_handler.py
Labels: feature

#284 Fixed off-by-1 error (skip 'Functions' view)
  angrmanagement/ui/workspace.py
Labels: bug

#285 Feat: Decompilation Change Callbacks
  angrmanagement/plugins/base_plugin.py
  angrmanagement/plugins/binsync/binsync_plugin.py
  angrmanagement/plugins/binsync/sync_view.py
  angrmanagement/plugins/plugin_manager.py
  angrmanagement/ui/dialogs/rename_node.py
  angrmanagement/ui/menus/sync_menu.py
  angrmanagement/ui/widgets/qccode_edit.py
  angrmanagement/ui/workspace.py
Labels: feature

#300 Feat: allow multiple functions passed in a context menu
  angrmanagement/plugins/base_plugin.py
  angrmanagement/plugins/binsync/binsync_plugin.py
  angrmanagement/plugins/plugin_manager.py
  angrmanagement/plugins/sample_plugin.py
  angrmanagement/ui/menus/function_context_menu.py
  angrmanagement/ui/widgets/qccode_edit.py
  angrmanagement/ui/widgets/qfunction_table.py
Labels: feature

#322 Feat: BinSync UI
  angrmanagement/data/sync_ctrl.py
  angrmanagement/plugins/binsync/binsync_plugin.py
  angrmanagement/plugins/binsync/info_tables/__init__.py
  angrmanagement/plugins/binsync/info_tables/func_info_table.py
  angrmanagement/plugins/binsync/info_tables/struct_info_table.py
  angrmanagement/plugins/binsync/info_view.py
  angrmanagement/plugins/binsync/sync_menu.py
Labels: feature, refactor

#325 Properly support high-DPI displays.
  angrmanagement/__main__.py
  angrmanagement/config/config_manager.py
  angrmanagement/plugins/plugin_manager.py
  angrmanagement/plugins/sample_plugin.py
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/widgets/qblock.py
  angrmanagement/ui/widgets/qblock_code.py
  angrmanagement/ui/widgets/qblock_label.py
  angrmanagement/ui/widgets/qdepgraph_block.py
  angrmanagement/ui/widgets/qdisasm_graph.py
  angrmanagement/ui/widgets/qfunction_header.py
  angrmanagement/ui/widgets/qgraph.py
  angrmanagement/ui/widgets/qgraph_object.py
  angrmanagement/ui/widgets/qinstruction.py
  angrmanagement/ui/widgets/qlinear_viewer.py
  angrmanagement/ui/widgets/qmemory_data_block.py
  angrmanagement/ui/widgets/qoperand.py
  angrmanagement/ui/widgets/qphivariable.py
  angrmanagement/ui/widgets/qproximitygraph_block.py
  angrmanagement/ui/widgets/qunknown_block.py
  angrmanagement/ui/widgets/qvariable.py
Labels: enhancement

#341 Find functions to rename using their addresses. Fix #336.
  angrmanagement/ui/dialogs/rename_label.py
  angrmanagement/ui/dialogs/rename_node.py
  angrmanagement/ui/main_window.py
  angrmanagement/ui/views/disassembly_view.py
  tests/test_rename_functions.py
Labels: bug

#343 Remove reference to CFG.model. Fix #334.
  angrmanagement/ui/views/code_view.py
Labels: bug

#354 ProximityGraph: Ensure scene exists before calling .update().
  angrmanagement/ui/widgets/qproximity_graph.py
Labels: bug
