Repository angr/angr-management, pull requests merged in 2021-03, with the labels that each got.

#217 Refactor graph layouters to remove hardcoded constants.
  angrmanagement/utils/graph_layouter.py
  angrmanagement/utils/tree_graph_layouter.py
Labels: refactor

#220 Support renaming variables in CodeView.
  angrmanagement/ui/dialogs/rename_variable.py
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/widgets/qccode_edit.py
Labels: feature

#223 added better visualization for function_name nodes
  angrmanagement/ui/documents/qcodedocument.py
Labels: refactor

#224 Function renaming
  .pylintrc
  angrmanagement/ui/dialogs/rename_node.py
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/widgets/qccode_edit.py
Labels: enhancement, feature

#232 Added a temporary fix for Mac menu bars
  angrmanagement/ui/main_window.py
Labels: bug

#233 Added Binsync Plugin
  angrmanagement/plugins/binsync/__init__.py
  angrmanagement/plugins/binsync/binsync_plugin.py
  angrmanagement/plugins/binsync/qteam_table.py
  angrmanagement/plugins/binsync/sync_config.py
  angrmanagement/plugins/binsync/sync_view.py
  angrmanagement/ui/main_window.py
  angrmanagement/ui/view_manager.py
  angrmanagement/ui/views/__init__.py
  angrmanagement/ui/workspace.py
Labels: feature, refactor

#218 Proximity graph view
  angrmanagement/ui/main_window.py
  angrmanagement/ui/menus/analyze_menu.py
  angrmanagement/ui/views/__init__.py
  angrmanagement/ui/views/proximity_view.py
  angrmanagement/ui/widgets/qgraph_arrow.py
  angrmanagement/ui/widgets/qproximity_graph.py
  angrmanagement/ui/widgets/qproximitygraph_block.py
  angrmanagement/ui/workspace.py
Labels: feature
