Repository angr/angr-management, pull requests merged in 2022-07, with the labels that each got.

#718 Pseudocode view: Support swapping binary expression operands.
  angrmanagement/ui/widgets/qccode_edit.py
Labels: feature

#719 Always attempt to use the Decompiler Clinic Cache
  angrmanagement/ui/widgets/qdisasm_graph.py
Labels: bug

#723 CoverageViewer: Optimize the implementation.
  angrmanagement/plugins/coverage/coverage.py
  angrmanagement/plugins/coverage/parse_trace.py
Labels: enhancement

#724 Fix the broken recent files feature.
  angrmanagement/config/config_manager.py
  angrmanagement/ui/main_window.py
  angrmanagement/ui/menus/file_menu.py
Labels: bug
