Repository angr/angr-management, pull requests merged in 2022-06, with the labels that each got.

#692 Display a progress dialog when loading angr db.
  angrmanagement/data/jobs/loading.py
  angrmanagement/ui/main_window.py
Labels: feature

#698 Support creating ternary expressions.
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/widgets/qccode_edit.py
Labels: feature

#699 Skip highlighting CFB item of unknown size in Hex view
  angrmanagement/ui/views/hex_view.py
Labels: bug

#704 PseudocodeView: Do not scroll down again after renaming variables.
  angrmanagement/ui/dialogs/rename_node.py
  angrmanagement/ui/views/code_view.py
  angrmanagement/ui/widgets/qdisasm_graph.py
Labels: enhancement

#707 Switch to tomlkit
  angrmanagement/config/config_manager.py
  angrmanagement/plugins/chess_manager/chess_url_handler.py
  angrmanagement/plugins/varec/varec.py
  setup.cfg
Labels: bug
