Repository angr/angr-management, pull requests merged in 2022-12, with the labels that each got.

#828 Set main window title
  angrmanagement/ui/main_window.py
Labels: bug

#830 Prefer Alt+Tab to Ctrl+Tab for view switching
  angrmanagement/ui/main_window.py
Labels: enhancement

#832 Save greyed out when no project loaded; `Menu` updates `QAction` to saved state on `set_action`
  angrmanagement/data/instance.py
  angrmanagement/ui/menus/file_menu.py
  angrmanagement/ui/menus/menu.py
Labels: bug, enhancement

#866 CodeTagging: Skip alignment functions.
  angrmanagement/data/jobs/code_tagging.py
Labels: enhancement

#865 Adaptively configure the number of VaRec workers based on binary sizes.
  angrmanagement/__main__.py
  angrmanagement/data/analysis_options.py
  angrmanagement/data/instance.py
  angrmanagement/ui/awesome_tooltip_event_filter.py
  angrmanagement/ui/dialogs/analysis_options.py
  angrmanagement/ui/views/code_view.py
Labels: enhancement
