Repository angr/angr-management, pull requests merged in 2023-03, with the labels that each got.

#928 Add initial Goto-Anything feature
  angrmanagement/ui/dialogs/command_palette.py
  angrmanagement/ui/main_window.py
Labels: feature

#936 CommandPalette: Fix an IndexError.
  angrmanagement/ui/dialogs/command_palette.py
Labels: bug

#937 Refactor: Fix ruff-TCH004 issues.
  angrmanagement/plugins/bughouse/ui/components_treeview.py
  angrmanagement/plugins/chess_manager/poi_plugin.py
  angrmanagement/plugins/chess_manager/target_selector.py
  angrmanagement/plugins/sample_plugin.py
  angrmanagement/plugins/seed_table/seed_table_plugin.py
  angrmanagement/plugins/source_viewer/source_viewer_plugin.py
Labels: refactor

#953 QOperand: Do not crash if variable manager is None.
  angrmanagement/ui/widgets/qoperand.py
Labels: bug

#950 HexView: Limit the maximum number of rows to display.
  angrmanagement/ui/views/hex_view.py
Labels: enhancement

#951 FeatureMap: Do not raise exceptions when encountering empty regions.
  angrmanagement/ui/widgets/qfeature_map.py
Labels: bug

#952 FunctionTable: Support displaying UEFI interface name in the binary column.
  angrmanagement/ui/widgets/qfunction_table.py
Labels: enhancement

#954 Expose CodeTagging as a configurable analysis.
  angrmanagement/data/analysis_options.py
  angrmanagement/data/instance.py
Labels: enhancement

#960 DisasmView: Prompt users about invalid selection targets of XRefs.
  angrmanagement/ui/widgets/qdisasm_base_control.py
Labels: enhancement
